### ISSUE TITLE
JSReport 2.8.0 standalone executable doesn't work

### ISSUE THREAD

**Issue by jakubin** [jsreport/jsreport#729]
I'm using a js-report standalone executable.
All worked fine with version 2.7.1. When I upgraded to 2.8.0 (https://github.com/jsreport/jsreport/releases/download/2.8.0/jsreport-win.zip), I got this error in logs each time I try to generate a report:
```
2020-06-18T09:54:20.122Z - info: Starting rendering request 5 (user: null)
2020-06-18T09:54:20.122Z - info: Rendering template { name: SampleReport, recipe: chrome-pdf, engine: handlebars, preview: false }
2020-06-18T09:54:20.165Z - warn: Rendering request 5 finished with error in 42 ms
2020-06-18T09:54:20.166Z - warn: Error when processing render request 5 Cannot find module 'pdfjs-dist/lib/core/cmap.js'
Require stack:
- D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\utils\processText.js
- D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\utils\pdfManipulator.js
- D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\proxyPdfUtilsHandlers.js
- D:\snapshot\jsreport\node_modules\jsreport-scripts\lib\createScriptProxy.js
- D:\snapshot\jsreport\node_modules\jsreport-scripts\lib\scriptEvalChild.js
- D:\snapshot\jsreport\node_modules\jsreport-core\lib\scriptExecModuleWrapper.js
- D:\snapshot\jsreport\node_modules\script-manager\lib\worker-servers.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath. Error: Cannot find module 'pdfjs-dist/lib/core/cmap.js'
Require stack:
- D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\utils\processText.js
- D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\utils\pdfManipulator.js
- D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\proxyPdfUtilsHandlers.js
- D:\snapshot\jsreport\node_modules\jsreport-scripts\lib\createScriptProxy.js
- D:\snapshot\jsreport\node_modules\jsreport-scripts\lib\scriptEvalChild.js
- D:\snapshot\jsreport\node_modules\jsreport-core\lib\scriptExecModuleWrapper.js
- D:\snapshot\jsreport\node_modules\script-manager\lib\worker-servers.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1370:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1249:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\snapshot\jsreport\node_modules\jsreport-pdf-utils\lib\utils\processText.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (pkg/prelude/bootstrap.js:1351:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
2020-06-18T09:54:20.166Z - warn: Error during processing request at http://localhost:5488/api/report

```

**Comment by pofider** [comment]
Thank you for the bug report. I confirm this is a regression issue.
We will fix it with the next update.
